### PR TITLE
Fix for #54

### LINKED ISSUE #52: test_multi_file_with_defaults fails
The constructor

```
Converter(input_paths=['inputs/*.nc'], input_multi_file=True).run()
```

on line 92 of `test_converter.py` produces the error

```
E           ValueError: When combine='by_coords', passing a value for `concat_dim` has no effect. To manually combine along a specific dimension you should instead specify combine='nested' along with a value for `concat_dim`.

../../../miniconda3/envs/nc2zarr/lib/python3.10/site-packages/xarray/backends/api.py:888: ValueError
```

See e.g. https://ci.appveyor.com/project/bcdev/nc2zarr/builds/41635265/job/sxxbuetiy680cwc1

### LINKED ISSUE #54: output/append_dim ignored
The configuration 

```yaml
output:
   append_dim: "year"
```

is currently ignored, `append_dim` value will be its default value `"time"`.

### PR DESCRIPTION
**Pull request by forman**
In this PR:

* Fixed broken unit level test (#52)
* If `input/multi_file` is specified, `concat_dim` is now optional: If `concat_dim` is given, the multi-file combination method is `"nested"`, otherwise `"by_coords"`, which was the former default. (See [xarray.open_mfdatset()](https://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html).) 
* Fixed ignored `output/append_dim` setting. (#54)

Closes #54
Closes #52

### CODE REVIEW

**Review by TonioF — APPROVED** [review]
The known s3fs issue aside, this looks good.

**Review by pont-us — CHANGES_REQUESTED** [review]
Looks good! My only request is to document the new concat_dim behaviour; I know it's described in CHANGES.md, but it would be useful to have it mentioned in a docstring in open_datasets and/or in the config template.

**Comment by pont-us** [comment]
> The known s3fs issue aside, this looks good.

The s3fs issue is now fixed in main, so CI should be green again as soon as this PR is merged.

**Comment by forman** [comment]
> Looks good! My only request is to document the new concat_dim behaviour; I know it's described in CHANGES.md, but it would be useful to have it mentioned in a docstring in open_datasets and/or in the config template.

Right. Will do asap.

**Comment by pont-us** [comment]
I merged the current main into this branch to fix the errors caused by the changed micromamba path and outdated s3fs version.

**Pull request merged**
